
            <div class="table-responsive">
                <table class="table table-hover table-sm">
                    <thead>
                    <tr>
                        <td rowspan="2">Наименование</td>
                        <td colspan="14">Основные характеристики</td>
                        <td colspan="6">Напольная плита BA</td>
                    </tr>
                    <tr>

                        <td>D</td>

                        <td>H</td>

                        <td>G</td>

                        <td>L</td>

                        <td>Макс. толщина станины</td>

                        <td>Максимальная нагрузка</td>

                        <td>Станки, кг</td>

                        <td>Плоскошлифовальные станки, кг</td>

                        <td>Фрезерные станки, кг</td>

                        <td>Токарные станки, кг</td>

                        <td>Пресса с частотой хода до 100/мин, кг</td>

                        <td>Эксцентриковые пресса и вырубные автоматы с частотой хода до 300/мин, кг</td>

                        <td>Ni</td>

                        <td>Вес, кг</td>

                        <td>B</td>

                        <td>A</td>

                        <td>T</td>

                        <td>b</td>

                        <td>d</td>

                        <td>Вес исполнения ВА, кг</td>
                    </tr>
                    </thead>

                    <tbody>
                    <tr id="bx_3966226736_315">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM333M12/">LM 3-33</a>
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            32
                        </td>
                        <td>
                            М12
                        </td>
                        <td>
                            90
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            2000
                        </td>
                        <td>
                            1200
                        </td>
                        <td>
                            420
                        </td>
                        <td>
                            600
                        </td>
                        <td>
                            420
                        </td>
                        <td>
                            1000
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            1,1
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_318">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM511/">LM 5-11</a>
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            41
                        </td>
                        <td>
                            M16x1,5
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            2,2
                        </td>
                        <td>
                            220
                        </td>
                        <td>
                            114
                        </td>
                        <td>
                            10
                        </td>
                        <td>
                            190
                        </td>
                        <td>
                            16
                        </td>
                        <td>
                            3,1
                        </td>
                    </tr>
                    <tr id="bx_3966226736_316">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM527/">LM 5-27</a>
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            41
                        </td>
                        <td>
                            М16х1.5
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            1400
                        </td>
                        <td>
                            1100
                        </td>
                        <td>
                        </td>
                        <td>
                            400
                        </td>
                        <td>
                        </td>
                        <td>
                            900
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            2,2
                        </td>
                        <td>
                            220
                        </td>
                        <td>
                            114
                        </td>
                        <td>
                            10
                        </td>
                        <td>
                            190
                        </td>
                        <td>
                            16
                        </td>
                        <td>
                            3,1
                        </td>
                    </tr>
                    <tr id="bx_3966226736_317">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM542/">LM 5-42</a>
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            41
                        </td>
                        <td>
                            М16х1.5
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            2200
                        </td>
                        <td>
                            1600
                        </td>
                        <td>
                            500
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            500
                        </td>
                        <td>
                            1300
                        </td>
                        <td>
                            950
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            2,2
                        </td>
                        <td>
                            220
                        </td>
                        <td>
                            114
                        </td>
                        <td>
                            10
                        </td>
                        <td>
                            190
                        </td>
                        <td>
                            16
                        </td>
                        <td>
                            3,1
                        </td>
                    </tr>
                    <tr id="bx_3966226736_319">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM555M16/">LM 5-55</a>
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            41
                        </td>
                        <td>
                            М16х1.5
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            4000
                        </td>
                        <td>
                            3000
                        </td>
                        <td>
                            1000
                        </td>
                        <td>
                            1500
                        </td>
                        <td>
                            1000
                        </td>
                        <td>
                        </td>
                        <td>
                            2000
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            2,2
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_320">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM660M20/">LM 6-60</a>
                        </td>
                        <td>
                            185
                        </td>
                        <td>
                            45
                        </td>
                        <td>
                            М20х1.5
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            58
                        </td>
                        <td>
                            3200
                        </td>
                        <td>
                            2500
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            1000
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            1800
                        </td>
                        <td>
                            1300
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            4
                        </td>
                        <td>
                            245
                        </td>
                        <td>
                            150
                        </td>
                        <td>
                            10
                        </td>
                        <td>
                            215
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            6,6
                        </td>
                    </tr>
                    <tr id="bx_3966226736_321">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM680/">LM 6-80</a>
                        </td>
                        <td>
                            185
                        </td>
                        <td>
                            45
                        </td>
                        <td>
                            М20х1.5
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            58
                        </td>
                        <td>
                            5000
                        </td>
                        <td>
                            3500
                        </td>
                        <td>
                            1200
                        </td>
                        <td>
                            2000
                        </td>
                        <td>
                            1200
                        </td>
                        <td>
                            3000
                        </td>
                        <td>
                            2300
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            4
                        </td>
                        <td>
                            245
                        </td>
                        <td>
                            150
                        </td>
                        <td>
                            10
                        </td>
                        <td>
                            215
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            6,6
                        </td>
                    </tr>
                    <tr id="bx_3966226736_322">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM666M20/">LM 6-66</a>
                        </td>
                        <td>
                            185
                        </td>
                        <td>
                            39
                        </td>
                        <td>
                            М20х1.5
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            58
                        </td>
                        <td>
                            5500
                        </td>
                        <td>
                            4000
                        </td>
                        <td>
                            2000
                        </td>
                        <td>
                            2800
                        </td>
                        <td>
                            2000
                        </td>
                        <td>
                            3500
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            4
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_323">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM765/">LM 7-65</a>
                        </td>
                        <td>
                            228
                        </td>
                        <td>
                            60
                        </td>
                        <td>
                            M24x1,5
                        </td>
                        <td>
                            140
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            8,5
                        </td>
                        <td>
                            300
                        </td>
                        <td>
                            197
                        </td>
                        <td>
                            15
                        </td>
                        <td>
                            265
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            15
                        </td>
                    </tr>
                    <tr id="bx_3966226736_324">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM7100M24/">LM 7-100</a>
                        </td>
                        <td>
                            228
                        </td>
                        <td>
                            60
                        </td>
                        <td>
                            М24х1.5
                        </td>
                        <td>
                            140
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                            7000
                        </td>
                        <td>
                            6400
                        </td>
                        <td>
                            1700
                        </td>
                        <td>
                            2300
                        </td>
                        <td>
                            1700
                        </td>
                        <td>
                            5000
                        </td>
                        <td>
                            4000
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            8,5
                        </td>
                        <td>
                            300
                        </td>
                        <td>
                            197
                        </td>
                        <td>
                            15
                        </td>
                        <td>
                            265
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            15
                        </td>
                    </tr>
                    <tr id="bx_3966226736_325">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM7150/">LM 7-150</a>
                        </td>
                        <td>
                            228
                        </td>
                        <td>
                            60
                        </td>
                        <td>
                            M24x1,5
                        </td>
                        <td>
                            140
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            8,5
                        </td>
                        <td>
                            300
                        </td>
                        <td>
                            197
                        </td>
                        <td>
                            15
                        </td>
                        <td>
                            265
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            15
                        </td>
                    </tr>
                    <tr id="bx_3966226736_326">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM777M24/">LM 7-77</a>
                        </td>
                        <td>
                            228
                        </td>
                        <td>
                            54
                        </td>
                        <td>
                            М24х1.5
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                            8000
                        </td>
                        <td>
                            7200
                        </td>
                        <td>
                            3000
                        </td>
                        <td>
                            3600
                        </td>
                        <td>
                            3000
                        </td>
                        <td>
                            6500
                        </td>
                        <td>
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                            8
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_327">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8200M30/">LM 8-200</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                            M30x2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            19
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_328">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8250/">LM 8-250</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                            М30х2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                            11000
                        </td>
                        <td>
                            11000
                        </td>
                        <td>
                            2500
                        </td>
                        <td>
                            3500
                        </td>
                        <td>
                            2500
                        </td>
                        <td>
                            10000
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            19
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_329">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8300/">LM 8-300</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            70
                        </td>
                        <td>
                            M30x2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            19
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_330">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8200X1/">LM 8-200x1</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            M30x2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            21
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_331">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8250X1/">LM 8-250x1</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            M30x2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            21
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_332">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM8300X1/">LM 8-300x1</a>
                        </td>
                        <td>
                            315
                        </td>
                        <td>
                            100
                        </td>
                        <td>
                            M30x2
                        </td>
                        <td>
                            160
                        </td>
                        <td>
                            80
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            30
                        </td>
                        <td>
                            21
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_611">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM325M12/">LM 3-25</a>
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            37
                        </td>
                        <td>
                            М12
                        </td>
                        <td>
                            90
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            1200
                        </td>
                        <td>
                            900
                        </td>
                        <td>
                            300
                        </td>
                        <td>
                            400
                        </td>
                        <td>
                            300
                        </td>
                        <td>
                            700
                        </td>
                        <td>
                            600
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    <tr id="bx_3966226736_610">
                        <td>
                            <a href="/vibroopory/reguliruemye-opory/lm/LM311M12/">LM 3-11</a>
                        </td>
                        <td>
                            120
                        </td>
                        <td>
                            37
                        </td>
                        <td>
                            М12
                        </td>
                        <td>
                            90
                        </td>
                        <td>
                            44
                        </td>
                        <td>
                            880
                        </td>
                        <td>
                            650
                        </td>
                        <td>
                        </td>
                        <td>
                            250
                        </td>
                        <td>
                        </td>
                        <td>
                            500
                        </td>
                        <td>
                            400
                        </td>
                        <td>
                            20
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
