<div class="table-responsive">
    <table class="table table-hover table-sm">
        <thead>
    <tr>
        <td>Наименование</td>
        <td>Вес, кг</td>
        <td>D</td>
        <td>H</td>
        <td>Максимальная нагрузка</td>
        <td>L</td>
        <td>G</td>
        <td>Ni</td>
        <td>Станки</td>
        <td>Пресса с частотой хода до 100/мин</td>
    </tr>
    </thead>

        <tbody>
    <tr id="bx_3966226736_541">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME160F/">LME 160</a>
        </td>
        <td>
            2,175
        </td>
        <td>
            162
        </td>
        <td>
            35-47
        </td>
        <td>
            2000
        </td>
        <td>
            120
        </td>
        <td>
            M16
        </td>
        <td>
            12
        </td>
        <td>
            1000
        </td>
        <td>
            1500
        </td>
    </tr>
    <tr id="bx_3966226736_534">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME185K/">LME 185</a>
        </td>
        <td>
            2,7
        </td>
        <td>
            185
        </td>
        <td>
            39-51
        </td>
        <td>
            5000
        </td>
        <td>
            130
        </td>
        <td>
            M20
        </td>
        <td>
            12
        </td>
        <td>
            2500
        </td>
        <td>
            3500
        </td>
    </tr>
    <tr id="bx_3966226736_540">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME120F/">LME 120</a>
        </td>
        <td>
            0
        </td>
        <td>
            120
        </td>
        <td>
            32-44
        </td>
        <td>
            1000
        </td>
        <td>
            100
        </td>
        <td>
            М12
        </td>
        <td>
            12
        </td>
        <td>
            600
        </td>
        <td>
            800
        </td>
    </tr>
    <tr id="bx_3966226736_536">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME80R/">LME 80</a>
        </td>
        <td>
            0,4
        </td>
        <td>
            80
        </td>
        <td>
            25-33
        </td>
        <td>
            300
        </td>
        <td>
            80
        </td>
        <td>
            M10
        </td>
        <td>
            80
        </td>
        <td>
            150
        </td>
        <td>
            250
        </td>
    </tr>
    <tr id="bx_3966226736_549">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME40K/">LME 40</a>
        </td>
        <td>
            0,055
        </td>
        <td>
            40
        </td>
        <td>
            15-20
        </td>
        <td>
            50
        </td>
        <td>
            30
        </td>
        <td>
            M5
        </td>
        <td>
            5
        </td>
        <td>
            40
        </td>
        <td>
            60
        </td>
    </tr>
    <tr id="bx_3966226736_539">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME230R/">LME 230</a>
        </td>
        <td>
            0
        </td>
        <td>
            229
        </td>
        <td>
            54-66
        </td>
        <td>
            7000
        </td>
        <td>
            180
        </td>
        <td>
            M24
        </td>
        <td>
            12
        </td>
        <td>
            3000
        </td>
        <td>
            4500
        </td>
    </tr>
    <tr id="bx_3966226736_543">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME315R/">LME 315</a>
        </td>
        <td>
            0
        </td>
        <td>
            315
        </td>
        <td>
            70-82
        </td>
        <td>
            9000
        </td>
        <td>
            200
        </td>
        <td>
            M30
        </td>
        <td>
            12
        </td>
        <td>
            5500
        </td>
        <td>
            7400
        </td>
    </tr>
    <tr id="bx_3966226736_537">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME80K/">LME 80</a>
        </td>
        <td>
            0,301
        </td>
        <td>
            80
        </td>
        <td>
            25-33
        </td>
        <td>
            300
        </td>
        <td>
            80
        </td>
        <td>
            М10
        </td>
        <td>
            8
        </td>
        <td>
            150
        </td>
        <td>
            250
        </td>
    </tr>
    <tr id="bx_3966226736_546">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME160R/">LME 160</a>
        </td>
        <td>
            1,91
        </td>
        <td>
            162
        </td>
        <td>
            35-47
        </td>
        <td>
            2000
        </td>
        <td>
            120
        </td>
        <td>
            М16
        </td>
        <td>
            12
        </td>
        <td>
            1000
        </td>
        <td>
            1500
        </td>
    </tr>
    <tr id="bx_3966226736_544">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME120R/">LME 120</a>
        </td>
        <td>
            0,955
        </td>
        <td>
            120
        </td>
        <td>
            32-44
        </td>
        <td>
            1000
        </td>
        <td>
            100
        </td>
        <td>
            М12
        </td>
        <td>
            12
        </td>
        <td>
            600
        </td>
        <td>
            800
        </td>
    </tr>
    <tr id="bx_3966226736_538">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME185R/">LME 185</a>
        </td>
        <td>
            0
        </td>
        <td>
            185
        </td>
        <td>
            39-51
        </td>
        <td>
            5000
        </td>
        <td>
            130
        </td>
        <td>
            M20
        </td>
        <td>
            12
        </td>
        <td>
            2500
        </td>
        <td>
            3500
        </td>
    </tr>
    <tr id="bx_3966226736_535">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME230K/">LME 230</a>
        </td>
        <td>
            3,555
        </td>
        <td>
            229
        </td>
        <td>
            54-66
        </td>
        <td>
            7000
        </td>
        <td>
            180
        </td>
        <td>
            M24
        </td>
        <td>
            12
        </td>
        <td>
            3000
        </td>
        <td>
            4500
        </td>
    </tr>
    <tr id="bx_3966226736_545">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME315K/">LME 315</a>
        </td>
        <td>
            8,741
        </td>
        <td>
            315
        </td>
        <td>
            70-82
        </td>
        <td>
            9000
        </td>
        <td>
            200
        </td>
        <td>
            M30
        </td>
        <td>
            12
        </td>
        <td>
            5500
        </td>
        <td>
            7400
        </td>
    </tr>
    <tr id="bx_3966226736_547">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME120K/">LME 120</a>
        </td>
        <td>
            0,835
        </td>
        <td>
            120
        </td>
        <td>
            32-44
        </td>
        <td>
            1000
        </td>
        <td>
            100
        </td>
        <td>
            М12
        </td>
        <td>
            12
        </td>
        <td>
            600
        </td>
        <td>
            800
        </td>
    </tr>
    <tr id="bx_3966226736_542">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME80F/">LME 80</a>
        </td>
        <td>
            0,475
        </td>
        <td>
            80
        </td>
        <td>
            25-33
        </td>
        <td>
            300
        </td>
        <td>
            80
        </td>
        <td>
            М10
        </td>
        <td>
            8
        </td>
        <td>
            150
        </td>
        <td>
            250
        </td>
    </tr>
    <tr id="bx_3966226736_548">
        <td>
            <a href="/vibroopory/reguliruemye-opory/lme/LME160K/">LME 160</a>
        </td>
        <td>
            1,84
        </td>
        <td>
            162
        </td>
        <td>
            35-47
        </td>
        <td>
            2000
        </td>
        <td>
            120
        </td>
        <td>
            М16
        </td>
        <td>
            12
        </td>
        <td>
            1000
        </td>
        <td>
            1500
        </td>
    </tr>
    </tbody>
    </table>
</div>